### PR TITLE
Fixed: #27 - Copy to clipboard button added

### PR DESCRIPTION
**Pull request by aniketgattani**
I have done the following:
1. Added clipboard.js CDN.
2. Added the copy to clipboard button.
3. Added an img file "clippy.svg" for the button in static/assets.

### CODE REVIEW

**Comment by mohitkh7** [comment]
you have hardcoded url for image inside button in base.html, line 31. which is not a preferred way.
use rather {% static 'shorturl/assets/clippy.png' %} and save image in shorturl/static/shorturl/assets/ folder.

**Comment by modihere** [comment]
@mohitkh7 well pointed out. I had missed that. That is actually a good practice. @aniketgattani i would advise you to do the same way.

**Comment by aniketgattani** [comment]
ohh thanks for pointing out @mohitkh7  and @modihere . On it. is the rest of the portion of the PR ok ?

**Comment by modihere** [comment]
I will review it later and let you know if any changes are needed.

**Comment by aniketgattani** [comment]
@modihere I have updated the branch and made the PR again plz review it.

**Comment by modihere** [comment]
screenshot from 2017-12-08 19-03-39
Just check when the copy button pops up beside the link the link tends to move a bit upward. Just pull it down to the middle of the text box.
And please change the background of the button to a better color. Or make it like the Github copy button.

**Comment by aniketgattani** [comment]
@modihere I have made the changes but I dont know why these errors have popped up :\

**Comment by aniketgattani** [comment]
@modihere can u check it now

**Pull request merged**
